<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>PopulationDataFacade.Api-2ef8f39a-5bd2-4a31-8abc-8921706566a7</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PopulationDataFacade.Core/PopulationDataFacade.Core.csproj" />
    <ProjectReference Include="../PopulationDataFacade.Infrastructure/PopulationDataFacade.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
